# Configuration file for GitHub Dependabot
# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Root directory for GitHub Actions is
    # the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "monthly"
  # Maintain dependencies for Bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
