# Jekyll configuration file.
# https://jekyllrb.com/docs/configuration/

# Site variables
# https://jekyllrb.com/docs/variables/#site-variables
title: ZhengYuan Loo
email: hello@zhengyuan.sg
description: |
  The diary of his adventures.
url: https://zhengyuan.sg

# Social links
linkedin_username: loozhengyuan
github_username: loozhengyuan

# Analytics
analytics:
  google: G-E04C3F20CK

# Directory configuration
source: src
destination: build

# Theme settings
theme: minima

# Frontmatter defaults
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      type: posts
      path: ""
    values:
      permalink: /blog/:title/

# Plugins
# https://jekyllrb.com/docs/plugins/
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
