name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Compile site
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build
